
name: Build iOS Tweak

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        echo "THEOS=$HOME/theos" >> $GITHUB_ENV
        echo "$HOME/theos/bin" >> $GITHUB_PATH
        
    - name: Build tweak
      run: |
        make package
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tweak-package
        path: packages/*.deb
